/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecemergency;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static tecemergency.Colores.*;

/**
 *
 * @author Melina
 */
public class Configuracion extends javax.swing.JFrame {
    JPanel panel = new JPanel();
    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        cmbEstructura.removeAllItems();
        cmbEstructura.addItem("COLA");
        cmbEstructura.addItem("HEAP");
        setSize(536,540);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblRojos = new javax.swing.JLabel();
        lblVerdes = new javax.swing.JLabel();
        lblAmarillos = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblEgresos = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        cmbEstructura = new javax.swing.JComboBox<>();
        spRojos = new javax.swing.JSpinner();
        spVerdes = new javax.swing.JSpinner();
        spAmarillos = new javax.swing.JSpinner();
        spEgresos = new javax.swing.JSpinner();
        lblEstructura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Configuración");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(150, 20, 220, 50);

        lblRojos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblRojos.setForeground(new java.awt.Color(51, 51, 51));
        lblRojos.setText("Rojos:");
        getContentPane().add(lblRojos);
        lblRojos.setBounds(40, 120, 100, 30);

        lblVerdes.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblVerdes.setForeground(new java.awt.Color(51, 51, 51));
        lblVerdes.setText("verdes:");
        getContentPane().add(lblVerdes);
        lblVerdes.setBounds(40, 190, 100, 30);

        lblAmarillos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblAmarillos.setForeground(new java.awt.Color(51, 51, 51));
        lblAmarillos.setText("amarillos:");
        getContentPane().add(lblAmarillos);
        lblAmarillos.setBounds(40, 260, 130, 30);

        lblCantidad.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(51, 51, 51));
        lblCantidad.setText("Cantidad consultorios:");
        getContentPane().add(lblCantidad);
        lblCantidad.setBounds(30, 70, 450, 30);

        lblEgresos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblEgresos.setForeground(new java.awt.Color(51, 51, 51));
        lblEgresos.setText("egresos:");
        getContentPane().add(lblEgresos);
        lblEgresos.setBounds(40, 330, 100, 30);

        btnAceptar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(200, 450, 120, 60);

        cmbEstructura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEstructura);
        cmbEstructura.setBounds(310, 400, 110, 30);
        getContentPane().add(spRojos);
        spRojos.setBounds(200, 120, 60, 30);
        getContentPane().add(spVerdes);
        spVerdes.setBounds(200, 180, 60, 30);
        getContentPane().add(spAmarillos);
        spAmarillos.setBounds(200, 260, 60, 30);
        getContentPane().add(spEgresos);
        spEgresos.setBounds(200, 330, 60, 30);

        lblEstructura.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblEstructura.setForeground(new java.awt.Color(51, 51, 51));
        lblEstructura.setText("estructura a utilizar:");
        getContentPane().add(lblEstructura);
        lblEstructura.setBounds(30, 400, 450, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/257a75c1-2119-4e74-b908-cf7a24d02f58.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -50, 570, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if ("0".equals(spRojos.getValue().toString()) || "0".equals(spVerdes.getValue().toString()) || "0".equals(spAmarillos.getValue().toString())){
            JOptionPane.showMessageDialog(panel, "Por favor, indique el numero de consultorios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if (cmbEstructura.getSelectedItem().equals("COLA")){
                LinkedList consRojos = LinkedList.getConsRojos();
                //Heap = null;
                for (int index = 0; index < consRojos.getPosition(); index++){
                    Consultorio consTemporal = new Consultorio(ROJO);
                    consRojos.insert(consTemporal);
                }
                LinkedList consAmarillos = LinkedList.getConsAmarillos();
                for (int index = 0; index < consAmarillos.getPosition(); index++){
                    Consultorio consTemporal = new Consultorio(AMARILLO);
                    consAmarillos.insert(consTemporal);
                }
                LinkedList consVerdes = LinkedList.getConsVerdes();
                for (int index = 0; index < consVerdes.getPosition(); index++){
                    Consultorio consTemporal = new Consultorio(VERDE);
                    consVerdes.insert(consTemporal);
                }
                new PantallaPrincipal(true).setVisible(true);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbEstructura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAmarillos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEgresos;
    private javax.swing.JLabel lblEstructura;
    private javax.swing.JLabel lblRojos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerdes;
    private javax.swing.JSpinner spAmarillos;
    private javax.swing.JSpinner spEgresos;
    private javax.swing.JSpinner spRojos;
    private javax.swing.JSpinner spVerdes;
    // End of variables declaration//GEN-END:variables
}
