/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecemergency;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Melina
 */
public class EstadoConsultorios extends javax.swing.JFrame {
    QueueConsultorios consVerdes = QueueConsultorios.getConsVerdes();
    QueueConsultorios consAmarillos = QueueConsultorios.getConsAmarillos();
    QueueConsultorios consRojos = QueueConsultorios.getConsRojos();
    JPanel panel = new JPanel();
    /**
     * Creates new form EstadoConsultorios
     */
    public EstadoConsultorios() {
        initComponents();
        setTable();
        setSize(595,590);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistro = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultorios = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        lblRegistro.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(51, 51, 51));
        lblRegistro.setText("REGISTRO DEL PACIENTE");

        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        lblTitulo.setText("Estado de los consultorios");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(100, 10, 380, 80);

        tblConsultorios.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        tblConsultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Color", "ID", "Estado", "Paciente"
            }
        ));
        jScrollPane1.setViewportView(tblConsultorios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 520, 450);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/257a75c1-2119-4e74-b908-cf7a24d02f58.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(-110, 0, 760, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setTable(){
        if (consVerdes == null && consRojos == null && consAmarillos == null){
            JOptionPane.showMessageDialog(panel, "No hay consultorios disponibles en este momento.", "Aviso", JOptionPane.ERROR_MESSAGE);
            hide();
        } else{
            DefaultTableModel model = new DefaultTableModel();
            tblConsultorios.setModel(model);
            model.addColumn("Color");
            model.addColumn("ID");
            model.addColumn("Estado");
            model.addColumn("Paciente");
            NodeConsultorio temp = consVerdes.getFront().getNext();
            for (int index = 0; index < consVerdes.getSize(); index++){
                if (temp.getElement().getPaciente() == null)
                    model.addRow(new Object[]{"Verde",temp.getElement().getId(),"Libre","-"});
                else
                    model.addRow(new Object[]{"Verde",temp.getElement().getId(),"Ocupado",temp.getElement().getPaciente().getFicha()});
                temp = temp.getNext();
            }
            if (consAmarillos.getSize() != 0){
                temp = consAmarillos.getFront().getNext();
                for (int index = 0; index < consAmarillos.getSize(); index++){
                    if (temp.getElement().getPaciente() == null)
                        model.addRow(new Object[]{"Amarillo",temp.getElement().getId(),"Libre","-"});
                    else
                        model.addRow(new Object[]{"Amarillo",temp.getElement().getId(),"Ocupado",temp.getElement().getPaciente().getFicha()});
                    temp = temp.getNext();
                }
            }
            temp = consRojos.getFront().getNext();
            for (int index = 0; index < consRojos.getSize(); index++){
                if (temp.getElement().getPaciente() == null)
                    model.addRow(new Object[]{"Rojo",temp.getElement().getId(),"Libre","-"});
                else
                    model.addRow(new Object[]{"Rojo",temp.getElement().getId(),"Ocupado",temp.getElement().getPaciente().getFicha()});
                temp = temp.getNext();
            }
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblConsultorios;
    // End of variables declaration//GEN-END:variables
}
