/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecemergency;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melina
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    boolean isQueue;
    LQueue filaRoja;
    LQueue filaAmarilla;
    LQueue filaVerde;
    QueueConsultorios consRojos = QueueConsultorios.getConsRojos();
    QueueConsultorios consVerdes = QueueConsultorios.getConsVerdes();
    QueueConsultorios consAmarillos = QueueConsultorios.getConsAmarillos();
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(boolean pIsQueue) {
        initComponents();
        isQueue = pIsQueue;
        filaRoja = new LQueue();
        filaAmarilla = new LQueue();
        filaVerde = new LQueue();
        setTable(consRojos, tblRojos);
        setTable(consVerdes, tblVerdes);
        setTable(consAmarillos, tblAmarillos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAmarillos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRojos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVerdes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnRegistro.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnRegistro.setText("REGISTRO");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro);
        btnRegistro.setBounds(20, 480, 130, 60);

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setText("estado c.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 410, 130, 58);

        tblAmarillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Consultorios disponibles"
            }
        ));
        jScrollPane2.setViewportView(tblAmarillos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(23, 50, 151, 150);

        tblRojos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Consultorios disponibles"
            }
        ));
        jScrollPane3.setViewportView(tblRojos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(551, 50, 151, 150);

        tblVerdes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Consultorios disponibles"
            }
        ));
        jScrollPane4.setViewportView(tblVerdes);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(292, 50, 151, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setTable(QueueConsultorios pQueue, JTable pTable){
        DefaultTableModel model = new DefaultTableModel();
        pTable.setModel(model);
        model.addColumn("Consultorios disponibles");
        NodeConsultorio temp = pQueue.getFront().getNext();
        for (int index = 0; index < pQueue.getSize(); index++){
            model.addRow(new Object[]{temp.getElement().getId()});
            temp = temp.getNext();
        }
    }
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        new Registro().setVisible(true);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new EstadoConsultorios().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAmarillos;
    private javax.swing.JTable tblRojos;
    private javax.swing.JTable tblVerdes;
    // End of variables declaration//GEN-END:variables
}
